-- House style, measured from the workspace's own past bids.
--
-- One row per workspace, rebuilt on demand. `metrics` is what was measured (so the UI can
-- show the user WHY the brief says what it says, rather than asking them to trust it) and
-- `brief` is the instruction text injected into the drafting prompts.
--
-- `brief` is generated by app/deterministic/style.py from thresholds, using only phrasing
-- written in that module. Nothing from the source documents reaches this column — a brief
-- assembled by reading untrusted proposals and then injected into every future drafting
-- prompt would be a permanent prompt-injection channel (G-6).

create table if not exists public.style_profiles (
  id           uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  metrics      jsonb not null default '{}',
  brief        text  not null default '',
  built_from   int   not null default 0,   -- how many past bids it was measured from
  built_by     uuid,
  updated_at   timestamptz not null default now(),
  created_at   timestamptz not null default now(),
  -- One current profile per workspace. workspace_id is the conflict target AND the scope
  -- column, so a service-role rebuild cannot reassign another workspace's row.
  unique (workspace_id)
);

alter table public.style_profiles enable row level security;

drop policy if exists style_profiles_workspace_all on public.style_profiles;
create policy style_profiles_workspace_all on public.style_profiles for all
  using (workspace_id = public.current_workspace_id())
  with check (workspace_id = public.current_workspace_id());

comment on column public.style_profiles.brief is
  'Templated from measurements only. Governs tone and shape; never licenses a claim, and '
  'contains no text taken from the source documents.';
